### ISSUE TITLE
but how to do a read and a write atomically?

### ISSUE THREAD

**Issue by the1mills** [npm/write-file-atomic#14]
I see the value in writing atomically, but are there any suggestions for

```
1. locking a file
2. reading from it
3. writing to it
4. releasing the lock
```

how do we do this (with Node.js)?

thanks for any help!

**Comment by iarna** [comment]
You'll need to use a file locking module and do basically exactly what you say there. I don't have any specific module recommendations—but the https://npmjs.com search is pretty good these days, so I'm pretty sure you'll find something.
