### ISSUE TITLE
getTmpname always returns the same hash

### ISSUE THREAD

**Issue by nhabuiduc** [npm/write-file-atomic#15]
The problem is because process.id and invocation are not string, convert to string will fix the problem, for example :
return  filename + '.' + MurmurHash3(__filename).hash(process.pid + '').hash((++invocations) + '').result()

Context: this library is used by configstore, which is used by bower, when running bower install in parallel, this problem causes the issue

**Comment by iarna** [comment]
Flurgh, a change I  just made. um, yes, sorry about that. I'm adding a test for this, thank you for opening this.
