### ISSUE TITLE
Weird problems with session-file-storage

### ISSUE THREAD

**Issue by DonMartin76** [npm/write-file-atomic#27]
Hello,

I am not quite sure this really fits here, and maybe it's not even an `write-file-atomic` issue (difficult to tell). But whatever: The update from 1.3.1 to 1.3.4 seems to cause valery-barysok/session-file-store#61, and subsequently also caused Haufe-Lexware/wicked.haufe.io#72.

For now, I had to pin version 1.3.1 (that fixes it for me) in my parent `package.json`, so that `session-file-store` also picks version 1.3.1.

Presumably, the following happens: The session file store tries to persist the session data, but that doesn't happen immediately, so that subsequent (more or less parallel) calls to the backend overwrites the session information, taking out e.g. the `user` information from it --> The user is not logged in, even if the login succeeded. Sometimes, the state was persisted, but not reflected immediately. Likewise with logging out (which sometimes was simply not possible).

I will check whether this can be fixed by rolling forward to `2.x`, and if so, file a PR for `session-file-store`.

Best regards, Martin

**Comment by valery-barysok** [comment]
Hi, it is known issue. See https://github.com/valery-barysok/session-file-store/issues/51

**Comment by valery-barysok** [comment]
@DonMartin76, the issue related to graceful-fs@4.1.11. you need to downgrade to 4.1.10

**Comment by iarna** [comment]
You may also be interested in the just landed https://github.com/npm/write-file-atomic/commit/8b550c0ee0294c932ff470ed0fb9be9292b94c88 which serializes writes to the same file, so they'll happen deterministicly.

**Comment by iarna** [comment]
Closing as it does seem that 2.x fixed the issue.
