### ISSUE TITLE
What means "atomic" in this context?

### ISSUE THREAD

**Issue by StanleySathler** [npm/write-file-atomic#32]
Hello guys,
I'd like to understand better what means "atomic" in this context. Mostly sure _atomic_ here means exactly the same thing that _atomic_ in general programming, but that's what I don't know.

Could you guys help me understanding that?

**Comment by MajorBreakfast** [comment]
It writes your data to a temporary file and then renames the file.
This avoids halfway written files under their final name in case your program is suddenly stopped (e.g. in case of a program crash or when your computer looses power)

**Comment by StanleySathler** [comment]
Thanks for the explanations @MajorBreakfast and @iarna. It's a lot more clear now. And sorry for taking too long to answer, Major, but I managed to lose this message somehow.

**Comment by iarna** [comment]
Hey it took me a loong time to answer too, no worries! =D
