### ISSUE TITLE
Return a promise

### ISSUE THREAD

**Issue by MajorBreakfast** [npm/write-file-atomic#33]
Since the library is already written with promises, it'd be nice if it could return a promise. I generally prefer promises over callbacks, because they're really nice to work with in conjunction with `async function`s 😋

**Comment by iarna** [comment]
Agreed, I would love a patch that makes it behave like Bluebird's `asCallback` method, eg, hybrid mode where a promise is always returned and a callback is used if one is provided.

**Comment by coreyfarrell** [comment]
@iarna what is the node.js support policy for this module?  Specifically are you open to a breaking change to require node.js 8?  This would allow use of util.promisify and async/await making it very simple to implement a promise API which still supported the callback argument.  I know it's a big jump from the currently supported versions so I understand if this idea is not acceptable.

**Comment by iarna** [comment]
@coreyfarrell This module currently supports node 4 up. Removing things from that list is a breaking change. The npm cli support policy is "any version supported by the Node Foundation", AND the list can only change on major version bumps. This seems like a generally solid rule to apply for libraries as well. Node 6 doesn't drop out of support until April 30th. After that date, a Node 8+ version could be released under a new major.

However, I should note that I [will not](https://npm.community/t/iarna-rebecca-turner-departing-npm/6575) be in a position to 👍 or 👎 changes like this when that date comes.

**Comment by coreyfarrell** [comment]
I hadn't realized they bumped the date, I thought April 1st was the EOL date (https://github.com/nodejs/Release/issues/421).

In any case I wish you the best on whatever comes next for you!

**Comment by sindresorhus** [comment]
> Node 6 doesn't drop out of support until April 30th. After that date, a Node 8+ version could be released under a new major.

That date has passed.

**Comment by coreyfarrell** [comment]
I've opened #44.  One thing that I'm not sure about is the `Promise` option.  In my current patch this option is still honored for the per file serialize logic only.  So a custom promise is only used for that one thing, everything else uses native promises.  I feel like my PR makes the Promise option fake.  Should support for custom promises be removed?

**Comment by isaacs** [comment]
I think if we're going to drop support for Node.js 6 in a semver major update, then dropping custom promises makes sense.  Native promises are very good now.
