### ISSUE TITLE
Code issues

### ISSUE THREAD

**Issue by jbrekelmans** [npm/write-file-atomic#35]
Some notes:
1. Unnecessary 'fs.unlink' in 'fail' in 'writeFile'. 'removeOnExit()' already unlinks the file.
2. Synchronous 'fs.unlinkSync' in asynchronous 'writeFile'. tmpfile should be unlinked asynchronously in all exit paths of 'writeFile'.

**Comment by iarna** [comment]
And this points to the fact that `removeOnExit()` wasn't remotely what it was supposed to be. `removeOnExit()` was supposed to be the`onExit` hook remover, and it was for the sync version. So there was no double unlink for the sync version.

Anyway, thanks for pointing this out
