### ISSUE TITLE
Jest run fails with EBADF: bad file descriptor

### ISSUE THREAD

**Issue by mayvancouver** [npm/write-file-atomic#39]
We have recently had the issue on CI when run jest in parallel.
jest: failed to cache transform results in: C:/Temp/jest/jest-transform-cache-
    Failure message: EBADF: bad file descriptor, close
       at Error (native)
       at Object.closeSync (node_modules/graceful-fs/graceful-fs.js:52:27)
        at Function.writeFileSync [as sync] (node_modules/write-file-atomic/index.js:228:16)

In the jest github, solution is rollback write-file-atomic to 2.4.1. 
https://github.com/facebook/jest/issues/7709.

I am wondering this is a bug of the package that need to be fixed?

**Comment by isaacs** [comment]
This should be fixed on 2.4.3.
