### ISSUE TITLE
worker_threads missing leads to webpack warning

### ISSUE THREAD

**Issue by james-criscuolo** [npm/write-file-atomic#41]
A project that I use (electron-json-storage) has begun using this project, and since they began using it a build warning has appeared when using webpack and angular AOT:
https://github.com/electron-userland/electron-json-storage/issues/126

copying relevant output here:
```
WARNING in ./node_modules/electron-json-storage/node_modules/write-file-atomic/index.js
Module not found: Error: Can't resolve 'worker_threads' in '/{path_to_my_project}/node_modules/electron-json-storage/node_modules/write-file-atomic'
 @ ./node_modules/electron-json-storage/node_modules/write-file-atomic/index.js
 @ ./node_modules/electron-json-storage/lib/storage.js
 @ {where my import is}
```
I see now based on the code that this is expected:
https://github.com/npm/write-file-atomic/blob/master/index.js#L17

Is this avoidable in some way? It seems to have no ill effects, but I'd like to be able to build without the warning if possible.

**Comment by Jack-Barry** [comment]
I was running Node `v11.4.0`, got this to go away by upgrading to `v11.7.0`. Looks like in order to use `worker_threads` Node had to be run with the `--experimental-worker` flag until `v11.7.0`. Credit for the insight goes to [this article](https://medium.com/@Trott/using-worker-threads-in-node-js-80494136dbb6).

**Comment by sindresorhus** [comment]
Relevant Webpack issue: https://github.com/webpack/webpack/issues/8826

**Comment by karimhossenbux** [comment]
For those having the issue with node `v10`, this could be a work around: https://www.npmjs.com/package/write-file-atomic

**Comment by james-criscuolo** [comment]
Closing this as Node 12 is now LTS, and it doesn't occur there.
