### ISSUE TITLE
Add changelogs for v3

### ISSUE THREAD

**Issue by popod** [npm/write-file-atomic#48]
Hi,

Please, can you update `CHANGELOG.md` with 3.0.0 changes and breaking changes ?

As I see, the only "big" changes are done in this commit: 5361569129007e80d3c1ab719cd697d682b82689. It seems to not have special changes, nor breaking expect the drop support for node 6 and before..

Thanks

**Comment by wraithgar** [comment]
going forward the changelog is automatic.  for the past you'll likely have to search git history, or submit a PR to update the changelog.
