### ISSUE TITLE
[FEATURE] Support for custom fs

### ISSUE THREAD

**Issue by privatenumber** [npm/write-file-atomic#62]
# What / Why
Support for passing in a custom fs (eg. [memfs](https://github.com/streamich/memfs) for writing to memory).

Currently using it for running fs related tests in-memory.

### Current Behavior

```js
writeFileAtomic(filePath, data, { mode: ..., chown: ... });
```
### Expected Behavior

```js
const fs = new memfs.Volume();
writeFileAtomic(filePath, data, { mode: ..., chown: ..., fs });
```

**Comment by wraithgar** [comment]
closing due to age.
