### ISSUE TITLE
reduce package size

### ISSUE THREAD

**Issue by jimmywarting** [npm/write-file-atomic#69]
Remove `is-typedarray` & `typedarray-to-buffer` to reduce dependencies?

Native solution:
```js
if (ArrayBuffer.isView(arr)) {
  data = Buffer.from(arr.buffer, arr.byteOffset, arr.byteOffset + arr.byteLength)
}
```

Better yet - don't convert it to a buffer. Node v10 supports writing any typedArray with the fs

**Comment by wraithgar** [comment]
Duplicate of https://github.com/npm/write-file-atomic/issues/86
